#!/usr/bin/env python3
"""Regenerate tests/data/catalog_digests.txt from catalog_source.json.

CHG-kilix-license replaces catalog_source.json with the accepted catalog
and re-runs this tool. The output file is never hand-edited.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tests" / "data" / "catalog_source.json"
OUTPUT = ROOT / "tests" / "data" / "catalog_digests.txt"
SCHEMA = "kilix.license.catalog-digest-source/v1"
_HEX = frozenset("0123456789abcdef")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_source(path: Path) -> tuple[bytes, list[str]]:
    data = path.read_bytes()
    parsed = json.loads(data.decode("utf-8"))
    if parsed.get("schema") != SCHEMA:
        raise SystemExit(f"catalog source schema must be {SCHEMA}")
    members = parsed.get("members")
    if not isinstance(members, list):
        raise SystemExit("catalog source members must be an array")
    digests: list[str] = []
    for index, item in enumerate(members):
        if isinstance(item, str):
            digest = item
        elif isinstance(item, dict) and "sha256" in item:
            digest = item["sha256"]
        else:
            raise SystemExit(f"members[{index}] must be a sha256 string or object")
        if len(digest) != 64 or set(digest) - _HEX:
            raise SystemExit(f"members[{index}] is not 64 lowercase hex")
        digests.append(digest)
    return data, sorted(set(digests))


def render(source_bytes: bytes, digests: list[str]) -> str:
    lines = [
        "# kilix-license catalog digest list",
        "# Generated by tools/regenerate_catalog_digests.py. Do not hand-edit.",
        f"# source: tests/data/catalog_source.json",
        f"# source_sha256: {sha256_hex(source_bytes)}",
        f"# count: {len(digests)}",
    ]
    lines.extend(digests)
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    output = OUTPUT
    source = SOURCE
    if argv[1:] == ["--stdout"]:
        source_bytes, digests = load_source(source)
        sys.stdout.write(render(source_bytes, digests))
        return 0
    source_bytes, digests = load_source(source)
    output.write_text(render(source_bytes, digests), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
